### ISSUE TITLE
Make issuer validation work with Kubernetes 1.21+ by default

### ISSUE THREAD

**Issue by liggitt** [hashicorp/vault-plugin-auth-kubernetes#125]
Issuer validation does not work by default with Kubernetes 1.21+, where bound service account tokens are enabled and the default issuer is no longer `kubernetes.io/serviceaccount`

It also is not possible to configure issuer validation to work during a 1.20 → 1.21 upgrade where tokens with both the legacy issuer and new issuer can be encountered.

Since a token review is performed, which ensures the token issuer is valid according to the kube-apiserver, the local issuer validation is an optimization. It seems like defaulting issuer validation off would be more compatible with Kubernetes 1.21+

**Comment by tomhjp** [comment]
As of Vault 1.9, issuer validation is now disabled by default, so I think we can close this one out as it should work by default, and users have a clean upgrade path if they disable issuer validation prior to upgrading kubernetes. Thanks for raising this @liggitt!
