### ISSUE TITLE
Mismatch in role list path in API vs docs

### ISSUE THREAD

**Issue by calvn** [hashicorp/vault-plugin-auth-kubernetes#14]
The [docs](https://www.vaultproject.io/api/auth/kubernetes/index.html#list-roles) indicates that role listing is under `auth/kubernetes/roles`, but the [actual path](https://github.com/hashicorp/vault-plugin-auth-kubernetes/blob/e6ff3b4fefe641225a7a81013337b3b62027b3a0/path_role.go#L18 ) is `auth/kubernetes/role`. We should change the API to use `/roles` (or vice-versa and update docs to indicate the path is `/role`).

**Comment by jefferai** [comment]
Def fix the documentation over the API in the short term.

**Comment by ewdurbin** [comment]
Doc fix merged in https://github.com/hashicorp/vault/pull/3708
