### ISSUE TITLE
docs should indicate that token_reviewer_jwt should be set to actual JWT token

### ISSUE THREAD

**Issue by rberlind** [hashicorp/vault-plugin-auth-kubernetes#15]
The docs at https://www.vaultproject.io/docs/auth/kubernetes.html#configuration give the following for writing to the auth/kubernetes/config path:

$ vault write auth/kubernetes/config \
    token_reviewer_jwt="reviewer_service_account_jwt" \
    kubernetes_host=https://192.168.99.100:8443 \
    kubernetes_ca_cert=@ca.crt

I had interpreted "reviewer_service_account_jwt" as a literal and actually used that.  I think it would be better if this were changed to "<your_reviewer_servicer_account_jwt>" using brackets and changing the name to indicate that this should be replaced with an actual JWT token.

We could also add brackets around your_service_account_jwt in the login example. But at least the name in this case makes it fairly clear that a user should not simply use that string.

**Comment by taylorsmithgg** [comment]
Please clarify this. I spent nearly an hour trial and erring to figure it out on my own.

**Comment by rberlind** [comment]
Hi @taylorsmithgg :  The value token_reviewer_jwt needs to be set to is a base64-decoded signed JSON Web Token (JWT).   Kuberetes JWT tokens do use the compact JWS format. Note that using token_reviewer_jwt is actually optional; this is indicated by https://www.vaultproject.io/api/auth/kubernetes/index.html#configure which says that if it is not set, the actual JWT used to login will be used to access the TokenReview API.

It is also worth noting that I used to be able to just pass in the literal string "reviewer_service_account_jwt" (since I had misinterpreted the documentation), but then this stopped working at some point.  That is actually good because "reviewer_service_account_jwt" is obviously not a valid JWT token.

**Comment by innovia** [comment]
This explains how to create a service account and get the ca.crt too 
https://kubernetes.io/docs/admin/authentication/#service-account-tokens
prior to configuring the auth/kubernetes/config

**Comment by avoidik** [comment]
would like to share correct link

https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/04-path-security-and-networking/401-configmaps-and-secrets#configure-kubernetes-auth-backend

**Comment by vbmade2000** [comment]
@innovia The link you mentioned doesn't exist.

**Comment by jacohend** [comment]
@avoidik 's link is literally the only sensical end-to-end documentation I've found anywhere. Both the hashicorp and coreos docs are frustratingly incomplete, and make unwarranted assumptions about what the developer knows. 

To reiterate: https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/04-path-security-and-networking/401-configmaps-and-secrets#configure-kubernetes-auth-backend is currently the only complete guide to using this backend.

**Comment by ekhaydarov** [comment]
can confirm these are the only dos that helped me. The official docs lead me into a frenzy of confusion. Some centralised, coherent docs would be great for everyone trying to get this hashicorp product running

**Comment by wmitchellUK** [comment]
> @avoidik 's link is literally the only sensical end-to-end documentation I've found anywhere. Both the hashicorp and coreos docs are frustratingly incomplete, and make unwarranted assumptions about what the developer knows.
> 
> To reiterate: https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/04-path-security-and-networking/401-configmaps-and-secrets#configure-kubernetes-auth-backend is currently the only complete guide to using this backend.

I wish I had discovered this in the beginning of my ramp up it would have saved me so much time .. agreed this feels like the only complete guide for k8s auth

**Comment by gdasson** [comment]
Well its well documented here: https://developer.hashicorp.com/vault/tutorials/kubernetes/agent-kubernetes
