### ISSUE TITLE
JWT signing algorithm ES384 became unsupported since version 0.13.0

### ISSUE THREAD

**Issue by jeroenvdheuvel** [hashicorp/vault-plugin-auth-kubernetes#159]
The JWT signing algorithm ES384 became unsupported after [switch from golang-jwt to cap+jose](https://github.com/hashicorp/vault-plugin-auth-kubernetes/commit/f706889f82e62f413c5465f59c4859a1ea8f6166#diff-e9cabdd28848f01142dd2db22533f3f7e7ffd87d064f2edbb7149f1b6d4bbecdL26). Likely due to a typo the RS384 algorithm is supported twice while ES384 is no longer supported.
![image](https://user-images.githubusercontent.com/5213151/187868813-888b2311-c14c-4936-a04d-71df10f359b0.png)

[Kubernetes officially supports this algorithm](https://github.com/kubernetes/kubernetes/blob/v1.25.0/pkg/serviceaccount/jwt.go#L152). That means that Kubernetes clusters that use this algorithm aren't able to upgrade to Vault 1.11 successfully. Because Vault 1.11.* is using version 1.13.* of the vault-plugin-auth-kubernetes.

**Comment by hsimon-hashicorp** [comment]
Closing as the linked PR was merged. :)
