### ISSUE TITLE
Support for multiple Kubernetes clusters

### ISSUE THREAD

**Issue by carpenterm** [hashicorp/vault-plugin-auth-kubernetes#19]
We have multiple Kubernetes clusters deployed in the same VPC. From what I can tell it is not possible to have more than one cluster registered with Vault, which means we would have to run multiple instances of Vault and Consul in the same VPC also, which we would like to avoid if possible. 

Is there a workaround or plan to support multiple clusters in the future?

**Comment by briankassouf** [comment]
Hi @carpenterm,

This is currently possible by enabling the kubernetes backend more than once:
```
vault auth-enable --path="kube-cluster-A" kubernetes
vault auth-enable --path="kube-cluster-B" kubernetes

vault write auth/kube-cluster-A/config kubernetes_host=HOSTA:8443 ....
vault write auth/kube-cluster-B/config kubernetes_host=HOSTB:8443 ...
```

**Comment by carpenterm** [comment]
Ah of course, yes that answers my question, thanks!

**Comment by ecejas** [comment]
With vault cli v1+ would be:
```
$vault auth enable --path="kube-cluster-A" kubernetes
$vault auth enable --path="kube-cluster-B" kubernetes
```

To see all your clusters plus other auth paths:
```
$vault auth list
```

Writing to the config stays the same.
