### ISSUE TITLE
Role Period not used on Auth tokens

### ISSUE THREAD

**Issue by Capitrium** [hashicorp/vault-plugin-auth-kubernetes#22]
Given the following role:
```
$ curl -s -H "X-Vault-Token: my-token" https://vault.external/v1/auth/kubernetes/role/test_aws_auth | jq '.'
{
...
  "data": {
    "bound_service_account_names": [
      "default"
    ],
    "bound_service_account_namespaces": [
      "default"
    ],
    "max_ttl": 0,
    "num_uses": 0,
    "period": 3600,
    "policies": [
      "test_aws"
    ],
    "ttl": 0
  },
...
}
```

Calling `vaultapi.Logical().Write()` returns an auth token without a `Period`:

```
resp, _ := vaultapi.Logical().Write("auth/kubernetes/login", {role:test_aws_auth,:jwt:my-jwt})
log.Printf("%+v", resp.Auth)

{
	ClientToken:my-client-token
	Accessor:my-client-token-accessor
	Policies:[default, test_aws]
	Metadata:map[
		role:test_aws_auth
		service_account_name:default
		service_account_namespace:default
		service_account_secret_name:default-token-12345
		service_account_uid:5481711b-eb16-4d7a-a10f-a9c3e9fff05e
	]
	LeaseDuration:3600
	Renewable:true
}
```

If I understand https://github.com/hashicorp/vault-plugin-auth-kubernetes/blob/master/path_login.go#L103 correctly, `Period` should be set in the token received from the `login` call to the value on the associated role.

Use case: I have a custom k8s controller responsible for authenticating with Vault, parsing a custom SecretClaim resource, and storing a k8s Secret with the actual leased secret. I'm finding that my kubernetes auth tokens are expiring despite their associated roles having a set period, and so all the leases created by the controller are getting revoked when their parent token expires.

**Comment by Capitrium** [comment]
Discussion continued [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/vault-tool/Ako7iSu5H6Q/8frRggNRBAAJ).

**Comment by dacohen** [comment]
We're having this same problem in Vault v0.10.1. Even if the role has a period set, the issued token does not. The linked discussion above doesn't have a solution, and while it looks like there were some code changes since this discussion, it looks like this is still an issue.

What's the best way to work around this bug? Is there a fix available?

**Comment by jefferai** [comment]
It's not a bug. Periods are only set directly on the token if the token was created via auth/token/create. Otherwise the period is controlled by the token issuer and its associated renew function.

**Comment by dacohen** [comment]
In that case, what's the best way to generate periodic tokens using the Kubernetes auth backend?

The documentation (https://www.vaultproject.io/api/auth/kubernetes/index.html#create-role) seems to indicate that creating a role with a period should cause tokens issued using that role to have that period, but if I'm understanding your comment correctly, this doesn't seem to be the case.

**Comment by jefferai** [comment]
When you create a token, does the TTL match the period value? When you renew it, does the TTL reset to the period value?
