### ISSUE TITLE
Error validating serviceaccount token when "pem_keys" are specified in the configuration

### ISSUE THREAD

**Issue by primeroz** [hashicorp/vault-plugin-auth-kubernetes#30]
Hi,

I have been trying to use the kubernetes authentication plugin and i was successful until i tried to use the "pem_keys" to validate the signature of the serviceaccount provided by the client pod as documented [here](https://www.vaultproject.io/api/auth/kubernetes/index.html#pem_keys)

I am running vault 0.10.1 and kubernetes 1.9.8 , i am using ECDSA Key to sign the serviceaccounts and i extracted the public key from the key using `openssl ec -in /etc/kubernetes/ssl/serviceaccount.key -pubout` 

I then updated the kubernetes auth config doing
```
 vault write auth/kubernetes/config kubernetes_host=URL token_reviewer_jwt=VAULT_SERVICE_TOKEN kubernetes_ca_cert=@/etc/ssl/certs/kubernetes-ca.pem pem_keys="PUBLIC_KEY_FROM_OPENSSL_COMMAND"
```

Doing a read show the key succesfully loaded in the vault config for kubernetes auth

Whenever i try to login from my client though i get an error 
```
~ $ curl -X POST -d @/dev/shm/payload.json -k https://vault:8200/v1/auth/kubernetes/login                                                           
{"errors":["asn1: structure error: length too large"]}
```

The very same command work as long as i don't have any "pem_keys" defined 

I also verified that the signature is correct for the public key using https://jwt.io/ 

Is there anything i am maybe missing in my configuration or anything else i am doing wrong ?

**Comment by jefferai** [comment]
What is the value of `PUBLIC_KEY_FROM_OPENSSL_COMMAND`?

**Comment by primeroz** [comment]
Hi Jeff.

If i understood correctly you want to see the output of the ssl command pubout key 
```
sudo openssl ec -in /etc/kubernetes/ssl/serviceaccount.key -pubout
read EC key
writing EC key
-----BEGIN PUBLIC KEY-----
MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEzpOY+XvrouGrV84L5BiIVg8/x85xsav6
cbDHnTXcwiTP830Aeg7w18dS4RylgiWFx8+E/BnKD1VSdHCfWFsskAQXAcRMIPbN
scOKeyb+rupBpled89vbPNlKd0CUg+Vo
-----END PUBLIC KEY-----
```

**Comment by primeroz** [comment]
So the only 2 way i manage to write the config to Vault is either by using New Lines for all lines or at least after and before the Headers.

All other cases i get an error because the string is not recognized as a valid public key

**Comment by jefferai** [comment]
I don't have a Kubernetes setup to test with, but I pulled out the function that parses the string and it works fine with your data:

```go
package main

import (
        "crypto/ecdsa"
        "crypto/rsa"
        "crypto/x509"
        "encoding/pem"
        "errors"
        "log"
)

func main() {
        {
                val, err := parsePublicKeyPEM([]byte(pemBytes))
                if err != nil {
                        panic(err)
                }
                log.Printf("%#v\n", val)
        }
        {
                val, err := parsePublicKeyPEM([]byte(pemBytesNewline))
                if err != nil {
                        panic(err)
                }
                log.Printf("%#v\n", val)
        }
}

// PasrsePublicKeyPEM is used to parse RSA and ECDSA public keys from PEMs
func parsePublicKeyPEM(data []byte) (interface{}, error) {
        block, data := pem.Decode(data)
        if block != nil {
                var rawKey interface{}
                var err error
                if rawKey, err = x509.ParsePKIXPublicKey(block.Bytes); err != nil {
                        if cert, err := x509.ParseCertificate(block.Bytes); err == nil {
                                rawKey = cert.PublicKey
                        } else {
                                return nil, err
                        }
                }

                if rsaPublicKey, ok := rawKey.(*rsa.PublicKey); ok {
                        return rsaPublicKey, nil
                }
                if ecPublicKey, ok := rawKey.(*ecdsa.PublicKey); ok {
                        return ecPublicKey, nil
                }
        }

        return nil, errors.New("data does not contain any valid RSA or ECDSA public keys")
}

const (
        pemBytes = `-----BEGIN PUBLIC KEY-----
MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEzpOY+XvrouGrV84L5BiIVg8/x85xsav6
cbDHnTXcwiTP830Aeg7w18dS4RylgiWFx8+E/BnKD1VSdHCfWFsskAQXAcRMIPbN
scOKeyb+rupBpled89vbPNlKd0CUg+Vo
-----END PUBLIC KEY-----`
        pemBytesNewline = "-----BEGIN PUBLIC KEY-----\nMHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEzpOY+XvrouGrV84L5BiIVg8/x85xsav6\ncbDHnTXcwiTP830Aeg7w18dS4RylgiWFx8+E/BnKD1VSdHCfWFsskAQXAcRMIPbN\nscOKeyb+rupBpled89vbPNlKd0CUg+Vo\n-----END PUBLIC KEY-----"
)
```
Can you try saving the value to a file (no special transformations), and using `pem_keys=@file` syntax in your `vault write` command?

**Comment by primeroz** [comment]
Hi Jeff, thanks for that ! 

I actually did the same thing short time ago and indeed the PublicKey is recognized and parsed properly by the 
```
if ecPublicKey, ok := rawKey.(*ecdsa.PublicKey); ok {
                        return ecPublicKey, nil
                }
```

I _think_ , with my extremely limited understanding of GO , is in the path_login.go , probably [here](https://github.com/hashicorp/vault-plugin-auth-kubernetes/blob/master/path_login.go#L216) where the Signature of the JWT token is checked against the public key.
This , to my understanding, happens before the call to the _tokenreview_ kubernetes api , and i can see on my apiserver that no tokenreview api call happen when the error is shown.

I think that the error is happening before the tokenreview api and it must be when the signature and the jwt token are compared. 

this would make sense since the write to the config succed and when no public_key is passed in the pem_keys argument that function exit just before the verify function

Just tried loading the files with the @File syntax and when trying to Login i get the same error as before

**Comment by jefferai** [comment]
Any chance you can add some logging into the code to try to track it down? For instance, is it coming from the JWS library via the `parsedJWT.Validate` call?

**Comment by primeroz** [comment]
I definetly can, but i am not sure i know how :) 

I am currently running the official container v0.10.2 from docker hub, i never built vault with external plugin but i guess i can figure it out ( if you got any docs to point me to that would be helpful ) . My understanding is that i can just rebuild this auth plugin and load it into vault , right ? 

If you could just provide me with the right syntax to add debug message i will add them into a bunch of places and will figure out where is bombing out

**Comment by jefferai** [comment]
The easiest thing might be to just build from Vault master (we've added a bit of debugging and pulled it in). You could then make a custom contianer that inherits from the 0.10.2 one but swaps in your binary.

**Comment by primeroz** [comment]
Will do an update, will be tomorrow though since is getting quite late here. 

thanks

**Comment by primeroz** [comment]
Hi @jefferai 

Error now confirm that the validation is failing with an error other than "Signature is invalid" 
https://github.com/hashicorp/vault-plugin-auth-kubernetes/blob/master/path_login.go#L252

```
$ curl -X POST -d @payload.json https://vault:8200/v1/auth/kubernetes/login
{"errors":["failed to validate JWT: asn1: structure error: length too large"]}
```

I can also confirm that on https://jwt.io the Public key correctly verify the token.

If it helps you track down the issue i could send you a Signed token privately

**Comment by jefferai** [comment]
That would be great! Can you send to jeff at the company I work for dot com?

**Comment by primeroz** [comment]
@jefferai  Great, i will give it a try as soon as it is available .

I can't see any reference to this bugfix in the changelog for vault, is it the fix in anyway ? 

Also i don't see an image for 0.10.3 on docker hub official repo, do you know when that should be available ?

**Comment by briankassouf** [comment]
@primeroz The docker image is now available on docker hub and this has been added to the CL.
