### ISSUE TITLE
Include namespace in display name with hyphen not colon

### ISSUE THREAD

**Issue by davidholsgrove** [hashicorp/vault-plugin-auth-kubernetes#38]
https://github.com/hashicorp/vault-plugin-auth-kubernetes/pull/31/ changed the display name to include the kubernetes namespace (yey!)

When using the Kubernetes auth method to generate MSSQL Database credentials, I now get a username with `v-kubernetes-{namespace}:` prefix, e.g;

`v-kubernetes-testing:v-GENPRD_0XA_LSTN-clie-cFbDNmp9WeGSJAo3hanx-1532477048`

previously the equivalent MSSQL username would have been;

`v-kubernetes-vault-aut-GENPRD_0XA_LSTN-clie-1qMciGW3fm0jNFAIGMTz-1531203590`

Comparing the same credential generated while using the AWS auth method, I get;

`v-aws-Role-Lab_ACP-AWS-GENPRD_0XA_LSTN-clie-e7L3UhmmeGCfKCQNwWlr-1532568250`

While a colon in a user name is valid for MSSQL, some older applications don't accept this unfortunately.
Can we change the display name to be hyphen separated instead of colon separated, which would be consistent with (at least) AWS Auth?

**Comment by catsby** [comment]
Closing b/c #39 was merged 😄
