### ISSUE TITLE
Error when vault login via kubernetes service account: "missing client token"

### ISSUE THREAD

**Issue by guptaarvindk** [hashicorp/vault-plugin-auth-kubernetes#41]
Hi Guys,

Pardon my knowledge about Vault, as I am just a beginner to Vault.  I am trying to setup Vault for kubernetes following this article.

https://medium.com/@gmaliar/dynamic-secrets-on-kubernetes-pods-using-vault-35d9094d169

After following the steps successfully including Vault setup and login etc, I dont see anything wrong with setting up vault or kubernetes SA setup. But  following all the steps correctly when another pod is trying to login to vault using K8s Service Account, I am seeing the error "missing client token". 

Can someone help me what could be the possible cause of this error. Just to reiterate, I am able to login to vault from vault client, but not able to login via kubernetes service account.

$ vault read auth/kubernetes/config
Key                   Value
---                   -----
kubernetes_ca_cert    -----BEGIN CERTIFICATE-----
MIIFVTCCAz2gAwIBAgIJANipEBaZrDFBMA0GCSqGSIb3DQEBCwUAMCUxIzAhBgNV
BAMMGmRpYW1hbnRpLXNpZ25lckAxNTMzNzY2Mzg1MB4XDTE4MDgwODIyMTMwNloX
DTI4MDgwNTIyMTMwNlowJTEjMCEGA1UEAwwaZGlhbWFudGktc2lnbmVyQDE1MzM3
NjYzODUwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDBYmFRzHpIcOR+
RwRcnNoe8s7ePjPN7KYRq/Ty/XL8etYfIAQoIG1vnzxNGFfqOQMhmU7y7v4+ber0
95A7nOgv8hAOm7g/b0iPNK15YQMrPUJXVRLW+v8MFaMnrw0apiBD2D+kJEw9ReHe
hF8JoXbeaKgtv2Z5sqCvpIeKII8lHjtwJxlHpexQIIKXveNacmEtfRDivwGjYNuH
jDEi1oX7bL/V4oYwS3y9KK3ePTdxIduHXUtbViQ4BJz94FeBbQWOGksXvxyR8OBe
4ng+UyTubIcVjMQara/AK3e1CIANCjcmVvlddHMLotPdhTeLSakkflv4IR8noatM
ysUKlcxbxgULUgxDRiefYSh0nUlOlP7NADQHBUE85GaE13Ewtmr/o8k5cMWVk1vB
yEIKgrCFq37TCklc9W1CQNztfMiFPkNdYe861amcpq43oQ9fBFrnhm2Ozqp7iq9M
cQ+KR1UGj1hTrFC2eIVEyd4iPNU2L8ZClrc9yFkh0pGYkykGS0ccQQlNEb+vbrYL
GYGG77KnSAFu6G11wgkb/K3dIxvmIDOGGhDdb5ZsrXDO3FJVdH75i+Xwsqs4HRZC
LrxFHqFUx9HmtE7B5dhsIX6uOpiQ6L+OU6BNgeac1Gh7bZSBdDTkgDM6Piw8c6at
yFpIB1Toz5zyZgjvvuT6g538RapnhwIDAQABo4GHMIGEMD8GA1UdIwQ4MDahKaQn
MCUxIzAhBgNVBAMMGmRpYW1hbnRpLXNpZ25lckAxNTMzNzY2Mzg1ggkA2KkQFpms
MUEwEgYDVR0TAQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAqQwHQYDVR0OBBYE
FEKdGQ54ZNd6RraemHipKMcEMniRMA0GCSqGSIb3DQEBCwUAA4ICAQBUMO3nnJhF
WUXRseCUibSBAShtLKOlltoANOSDSQ+GkNxjHmARyR7eFc9XMFyOXMsSC1HvP0IN
pdymebbzKPpevkbaIqyS1m0/lZYLbvuxzQF+IrPGQbwTtAWic3k7wwyDVVizm9Rq
s/SemiKcrAdCHYMxeKMctWiXwGXwwuv22D8dIjew+mO5zs5/IOYsfd0RCsiZl4HI
WsHGiyZ/oJ0NBTmP8F90Q2fVTHWGwdExWQQiDMXpI11orPcivmxl5Pt3oGZzFiTj
5lqlgVejYuNJ2s81GbVDWv3DIJN7Q9iqHb5Mxshf54V/E2zzKl/I4A4ZbBSY7Lie
reSurDCChR+j82XOO3D6NIIhHyUTcKNOVKdnzeFG2V+VXwQEOinvXTYvBW9YJpQb
8GCCNvrpfTIdnU/grzLPre14xSYLqeIfGD63ABq3vfh/GrPo1niX2ce5EtjXUEvM
tdouZKKyJ4wI9MDy/xvd9726qP+aoL3Z0TGptmpLVhoV9OkRmewkoxaYVp+w296F
4ewSZEJfd3dgBa3uPJPIXh7r+bfqATTfjgf6ZNL6aJufAi8pve8r7ksOfEs3Q51L
I2lTxwZ5aVUoe6BH96rXsbInQvMITjSqJb9zguhIgh7CdaqLcJj98bco0mJB2hnD
PAm55R3fhMzKx5hcXqnRHo+uqGjYLFh+kA==
-----END CERTIFICATE-----
kubernetes_host       https://172.16.220.102:443
pem_keys              []

$ kubectl run tmp --rm -i --tty --serviceaccount=postgres-vault --image alpine
/ # apk update
/ # apk add curl postgresql-client jq

/ # echo $KUBE_TOKEN
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InBvc3RncmVzLXZhdWx0LXRva2VuLWh6eHZnIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InBvc3RncmVzLXZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYWUzYzdjZWEtYTY3Ni0xMWU4LWE5MmEtYTRiZjAxNGIyOWZjIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmRlZmF1bHQ6cG9zdGdyZXMtdmF1bHQifQ.YrvlggZgckoW962gCXkh0kjQVeA-qkUf0nf1bf168XxfJhMgi40Xaof1Y_3Iy_CYukI_b_PiGdKw6ttkDk3gc1C0AzTE3fln1qKaWd7z6VvLdDXvLwdbDSmQ14t9Z4A-PU1OJkauM8b0o9hadmRYET6Liv8GnBQrEAf7lU-kVQDfRpzbY1khT8CGzVZJe-9lifAHmxHD4zYFhoyMoFp7X0moIubSsKI91dEaRNuUEFJrMYBpo0shnKWTi9H0G9HbDQygIEtMMosBRJtBNqE8yQ5ibZjWnJpwSNwQBLWnG9rpm5aK-GvG5-NRdwvw4q0cp59b2Gb7fovNoWxDS8YD4Q

/ # VAULT_K8S_LOGIN=$(curl --request POST --data '{"jwt": "'"$KUBE_TOKEN"'", "role": "postgres"}' http://masked-beetle-vault:8200/v1/auth/kubernetes/login)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   941  100    36  100   905   6000   147k --:--:-- --:--:-- --:--:--  183k
/ # echo $VAULT_K8S_LOGIN
{"errors":["missing client token"]}

Thanks,
-Arvind

**Comment by sethvargo** [comment]
Did you enable the kubernetes auth method? I don't see any calls to `vault auth enable kubernetes` or similar?

**Comment by guptaarvindk** [comment]
Yes I did enable kubernetes auth. I followed all the steps in that blogpost, Just didnt pasted the whole output here to keep is short.

**Comment by leochu** [comment]
@guptaarvindk The instructions in the blogpost deploys 3 instances of Vault and enables the Kubernetes auth backend once using DNS.  You would have to either enable the Kubernetes auth backend in all 3 servers or scale the cluster down to 1 server.

**Comment by catsby** [comment]
Hello – It's been a few weeks with no word, so I'm going to close this issue for now. It seems reasonable that the above comment explains it (3 instances, each with their own dev mode and needing the same backend initialized). If you feel closing is not correct, please let us know if you can provide and new information and I'll be happy to re-open and take another look.

Thanks!
