### ISSUE TITLE
Login error using service account verification keys

### ISSUE THREAD

**Issue by gmr** [hashicorp/vault-plugin-auth-kubernetes#42]
I'm trying to setup Vault/K8s integration with Tectonic Kubernetes using service account verification keys instead of a CA cert. It does not seem to properly validate the JWT key.

## Versions:
- Tectonic Kubernetes 1.9.6
- Vault 0.11.1

## Example:
Configured using public key verification, login fails:

```
~ # ./vault write auth/kubernetes/login role=vault-auth jwt=${JWT_TOKEN}
Error writing data to auth/kubernetes/login: Error making API request.

URL: PUT https://vault.service.testing.consul/v1/auth/kubernetes/login
Code: 500. Errors:

* invalid character '<' looking for beginning of value
```

The JWT and key pass validation at jwt.io: [link](https://jwt.io/#debugger-io?token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJ2YXVsdC1yZXZpZXdlci10b2tlbi05a2Z0ayIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJ2YXVsdC1yZXZpZXdlciIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImJlZDNlMmQwLWNlNTQtMTFlOC04NjkwLTIyY2I4MGFkZDBmZCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTp2YXVsdC1yZXZpZXdlciJ9.DzWBl1ALDaGctzEtpwLIizK5B491L2nJJnRUbZk0yJtSW-EOKmTxLVTazL2KJUb69J6fKZSAi5W_bAhvJQnKt4Gza5uGpDs-agcpEDp3k5kGaXP7ae2wRZcmdbWFXQkn_olx0OOGIs0egIMZ7Op8Q0i446CPyrIdotQL1RVh_bXuTm5Vd6KoFY2dy1WmhkLA-nPazqOzU4R-xnuDWAKsNmqxrQKwlhWqK8g5vdDHojcHIu6qc-VOLZaub-PFQOoUcKSBqEJu0s5WAjCznl2vfpTkmnDiP7h5Y29cr3qvEE_P1WIf4mxIUFerXyo2NeDiEtB-B9Rwlj-dqIjBlhq9gA&publicKey=-----BEGIN%20PUBLIC%20KEY-----%0AMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwzbaW%2FmLp3btu9tkpT7k%0Asupji8h6cXnM6QXZJE%2BBUc0HlnHksDWbxGZDGS1blluPj3GfebgvIrcaVXJ%2FPhzp%0AlFKuuzHjQm%2F1Qzqq294ZkD9o%2B0zP%2BQ5fcNfWIu2r9kf%2FElzQLP7DVvkfLvKyLdCq%0A7pvWLNBNV8JBThlECMuSdx14JMtcwQJx9%2Bz70PiMFcN2Dv4hBW0FtkvcpUsMQJmz%0Ai31%2FsUuzNLx8ee19N2Xiym4G3xruhweW6veJ%2F6S9oSMyD1HbHPZJDW3908YFab1H%0AxAZVdUsNwC1RDIa4eeUaYeVxdbr1pCuzUMdmrlGdVDWyacp4OBY5am1g7vf5vbN8%0AWwIDAQAB%0A-----END%20PUBLIC%20KEY-----%0A) (note that the link will fail to validate the signature due to an encoding issue in their link gen, but replace the key with the value in this issue and you'll see it passes).

I do not think that the CA cert based signing is how things are done in Tectonic K8s as when I paste the CA value for the K8s cluster in jwt.io the signature fails. When I use the CA based setup in vault for the k8s cluster, I get a x509 cert error.

## Setup Script:
```bash
#!/bin/bash
SA_NAME="vault-reviewer"
K8S_HOST=${K8S_HOST:-"https://vault.service.testing.consul:443"}
SECRET=$(kubectl get sa $SA_NAME --namespace=kube-system -o jsonpath='{.secrets[0].name}')
VAULT_JWT=$(kubectl get secret $SECRET --namespace=kube-system -o jsonpath="{.data['token']}" | base64 -D)

vault auth enable kubernetes
vault write auth/kubernetes/config \
  token_reviewer_jwt="$VAULT_JWT" \
  kubernetes_host="$K8S_HOST" \
  pem_keys="${VAULT_JWT}"

vault write auth/kubernetes/role/vault-auth \
  bound_service_account_names=vault-auth \
  bound_service_account_namespaces=pse \
  policies=kube-auth \
  period=60s
```

## Public Key:
```
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwzbaW/mLp3btu9tkpT7k
supji8h6cXnM6QXZJE+BUc0HlnHksDWbxGZDGS1blluPj3GfebgvIrcaVXJ/Phzp
lFKuuzHjQm/1Qzqq294ZkD9o+0zP+Q5fcNfWIu2r9kf/ElzQLP7DVvkfLvKyLdCq
7pvWLNBNV8JBThlECMuSdx14JMtcwQJx9+z70PiMFcN2Dv4hBW0FtkvcpUsMQJmz
i31/sUuzNLx8ee19N2Xiym4G3xruhweW6veJ/6S9oSMyD1HbHPZJDW3908YFab1H
xAZVdUsNwC1RDIa4eeUaYeVxdbr1pCuzUMdmrlGdVDWyacp4OBY5am1g7vf5vbN8
WwIDAQAB
-----END PUBLIC KEY-----
```

## JWT:
```
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJ2YXVsdC1yZXZpZXdlci10b2tlbi05a2Z0ayIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJ2YXVsdC1yZXZpZXdlciIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImJlZDNlMmQwLWNlNTQtMTFlOC04NjkwLTIyY2I4MGFkZDBmZCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTp2YXVsdC1yZXZpZXdlciJ9.DzWBl1ALDaGctzEtpwLIizK5B491L2nJJnRUbZk0yJtSW-EOKmTxLVTazL2KJUb69J6fKZSAi5W_bAhvJQnKt4Gza5uGpDs-agcpEDp3k5kGaXP7ae2wRZcmdbWFXQkn_olx0OOGIs0egIMZ7Op8Q0i446CPyrIdotQL1RVh_bXuTm5Vd6KoFY2dy1WmhkLA-nPazqOzU4R-xnuDWAKsNmqxrQKwlhWqK8g5vdDHojcHIu6qc-VOLZaub-PFQOoUcKSBqEJu0s5WAjCznl2vfpTkmnDiP7h5Y29cr3qvEE_P1WIf4mxIUFerXyo2NeDiEtB-B9Rwlj-dqIjBlhq9gA
```

## UI Screenshot

![screen shot 2018-10-15 at 2 31 15 pm](https://user-images.githubusercontent.com/49469/46970416-0225e380-d087-11e8-8b89-e44880364b13.png)

Would you be so kind as to point me in the right direction as to either what I am doing wrong?

**Comment by jiang-wei** [comment]
did you try this? https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/04-path-security-and-networking/401-configmaps-and-secrets#configure-kubernetes-auth-backend

**Comment by tomhjp** [comment]
Sorry to have left this stale for so long. Today, I'd recommend using [JWT](https://www.vaultproject.io/docs/auth/jwt) auth to verify JWTs if I understand correctly, as it sounds like you wanted to verify the JWTs offline, without querying the k8s API? If using the Kubernetes API is fine, then Kubernetes will verify the signature itself anyway, so I would recommend omitting the `pem_keys` parameter entirely.

We also now have a specific section on setting up JWT auth to verify Kubernetes tokens [here](https://www.vaultproject.io/docs/auth/jwt/oidc_providers#kubernetes), if that's of interest.

It looks like the setup script has a typo at `pem_keys="${VAULT_JWT}"`, but I assume that wasn't the issue here.
