### ISSUE TITLE
service account name not authorized

### ISSUE THREAD

**Issue by awolde** [hashicorp/vault-plugin-auth-kubernetes#49]
Im trying to get the k8s plugin to work with vault. I'm setting this up in GKE.
The documentation on how to use this plugin is incomplete. So I followed these steps pretty much - https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/04-path-security-and-networking/401-configmaps-and-secrets#start-vault-server-on-ec2

Once I launch my pod, login to the shell and do `curl     --request POST     --data "{\"jwt\": \"$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)\" , \"role\": \"demo\"}" $VAULT_ADDR/v1/auth/kubernetes/login`, I'm getting `{"errors":["service account name not authorized"]}`. 

The only difference is I'm running this in GKE rather than AWS. Any help would be appreciated.

**Comment by briankassouf** [comment]
How did you configure the `demo` role? Sounds like whatever service account you are using authorized to use the role

**Comment by awolde** [comment]
Here are the steps @briankassouf 
```
$ kubectl apply -f rbac.yaml
rbac.yaml
===
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-tokenreview
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: vault-tokenreview
  namespace: default
===
$ export K8S_VAULT_SA_SECRET=$(kubectl get serviceaccount vault-tokenreview -o json | jq -r .secrets[0].name)
$ kubectl get secret ${K8S_VAULT_SA_SECRET} -o json | jq -r '.data["ca.crt"]' | base64 -D > ca.crt
$ kubectl get secret ${K8S_VAULT_SA_SECRET} -o json | jq -r '.data["token"]' | base64 -D > sa.token

$ vault write auth/kubernetes/config  kubernetes_host=https://api-ip:443 kubernetes_ca_cert=@ca.crt token_reviewer_jwt=@sa.token

$ vault write auth/kubernetes/role/demo     bound_service_account_names=vault-tokenreview  bound_service_account_namespaces=default     policies=kube-auth     ttl=48h

$ vault policy write kube-auth kube-auth.hcl

kube-auth.hcl
===
path "secret/creds" {
  capabilities = ["read"]
}
===
```

**Comment by briankassouf** [comment]
@awolde And is the service account defined in the pod deployment the `vault-tokenreview` one?

**Comment by awolde** [comment]
Ahhhh! Nailed it @briankassouf. That's the part I was missing. Thanks so much! Works as expected.

**Comment by briankassouf** [comment]
Great! Also the Service Account you use to Auth does not need to be the same one you use for TokenReview. You can configure the role to accept another service account and can manage the RBAC roles for the two accounts separately.

**Comment by rayterrill** [comment]
@briankassouf is there an example of this "the Service Account you use to Auth does not need to be the same one you use for TokenReview. You can configure the role to accept another service account and can manage the RBAC roles for the two accounts separately." somewhere? This is exactly what I'm looking to do and can't quite get it dialed in.
