### ISSUE TITLE
Add ability to restrict login based on client IP

### ISSUE THREAD

**Issue by shelby-moore** [hashicorp/vault-plugin-auth-kubernetes#51]
This is a feature request for something similar to how you can restrict login/token usage by specifying a CIDR range when creating a user in the userpass backend (https://www.vaultproject.io/api/auth/userpass/index.html#bound_cidrs). Ideally I would like to restrict login using the kubernetes auth method to IPs belonging to my kubernetes cluster.

**Comment by rumenvasilev** [comment]
I believe this has been added with https://github.com/hashicorp/vault-plugin-auth-kubernetes/pull/67
https://www.vaultproject.io/api/auth/kubernetes/index.html#token_bound_cidrs

**Comment by jefferai** [comment]
Correct, it was added in #67, I just didn't know about this issue. Thanks for the pointer!
