### ISSUE TITLE
Getting "missing client token" when using --path for multiple kubernetes cluster.

### ISSUE THREAD

**Issue by justogaiht** [hashicorp/vault-plugin-auth-kubernetes#54]
Hello,
i have two k8s clusters and im trying to integrate both to the same vault instance. Trying the solution proposed with "--path=k8s-2" proposed in #19 i am getting "missing client token". I believe that its caused by the default endpoint that k8s is validating token "/v1/auth/kubernetes/login" instead of "/v1/auth/k8s-2/login". 

there is something that im missing at k8s config during vault integration?

**Comment by briankassouf** [comment]
Could you provide more information about the commands you are running and when you get the missing token error?

**Comment by ErikLundJensen** [comment]
The path starts from /v1/auth/kubernetes
There by the login will look like:
```
vault write auth/kubernetes/k8s-2/login role=myrole jwt=@token
```

In this example I have enabled kubernetes by using this curl command:
```
curl \
    -H "X-Vault-Token: $VAULT_TOKEN" \
    --request POST \
    --data '{ "type":"kubernetes" }' \
    "https://localhost:8200/v1/sys/auth/kubernetes/test" 
```

**Comment by jefferai** [comment]
In your output you show that you have enabled the auth method at `kubernetes/test` but you're trying to log in to `kubernetes/k8s-2`

**Comment by seangallavan** [comment]
I believe I am experiencing the same problem with a custom mount point giving a `missing client token` error. To test this, I have two mount points with identical information. The `kubernetes` mount point works while the `k8s-dev-aws` mount point does not. The configuration should be identical and use the same service account on k8s. Doing a little research, it looks like the endpoint `auth/k8s-dev-aws/login` may not be open to unauthorized clients

**Configuration**
```vault@ip-172-31-1-186:~$ vault read auth/kubernetes/config
Key                   Value
---                   -----
kubernetes_ca_cert    -----BEGIN CERTIFICATE-----
redacted
-----END CERTIFICATE-----
kubernetes_host       https://internal-api-dev-kops-k8s-local-1hf70q-955663663.us-east-1.elb.amazonaws.com:443
pem_keys              []

vault@ip-172-31-1-186:~$ vault read auth/k8s-dev-aws/config
Key                   Value
---                   -----
kubernetes_ca_cert    -----BEGIN CERTIFICATE-----
redacted
-----END CERTIFICATE-----
kubernetes_host       https://internal-api-dev-kops-k8s-local-1hf70q-955663663.us-east-1.elb.amazonaws.com:443
pem_keys              []```

**Role**
```vault@ip-172-31-1-186:~$ vault read auth/kubernetes/role/app-role-app-info
Key                                 Value
---                                 -----
bound_cidrs                         []
bound_service_account_names         [app-info]
bound_service_account_namespaces    [default]
max_ttl                             0s
num_uses                            0
period                              0s
policies                            [app-policy-app-info app-server-policy]
ttl                                 0s

vault@ip-172-31-1-186:~$ vault read auth/k8s-dev-aws/role/app-role-app-info
Key                                 Value
---                                 -----
bound_cidrs                         []
bound_service_account_names         [app-info]
bound_service_account_namespaces    [default]
max_ttl                             0s
num_uses                            0
period                              0s
policies                            [app-policy-app-info app-server-policy]```

**Comment by seangallavan** [comment]
Okay, this looks to be a real problem. I have two identically configured mount points, `kubernetes` and `k8s-dev-aws`, and only the custom mount point responds with a `missing client token` error. They use the same k8s information as well. The only difference is the mount point. This should be easy to verify.

**Comment by NandoTheessen** [comment]
We're facing the same issue. When using the "normal" auth/kubernetes endpoint everything is fine, however once we start deviateing and using custom mount points, we start seeing "missing client token" errors.

**Comment by mbrancato** [comment]
@NandoTheessen can you maybe elaborate on what you did here? It sounds like you did `role=mypath/myrole` ? are you referring to the auth method as the backend?

**Comment by Mark-McCracken** [comment]
Hi, @NandoTheessen, I'm also struggling with this issue, can you explain what steps you took to resolve this? My injector gets the following error: 

```sh
[INFO]  auth.handler: authenticating
[ERROR] auth.handler: error authenticating: error="Error making API request.
URL: PUT https://vault.livescore.co.uk/v1/auth/kubernetes/login
Code: 400. Errors:
* missing client token" backoff=1.406818745
```
But I think the url should be whatever path I've set for my cluster.

**Comment by tomhjp** [comment]
I'm going to close this out as stale. For reference, the canonical form for enabling the auth engine at custom mounts is as follows:

```bash
# Enable
vault auth enable -path=my-k8s-cluster kubernetes

# Configure
vault write auth/my-k8s-cluster/config kubernetes_host=...

# Create a role
vault write auth/my-k8s-cluster/role/foo bound_service_account_names=... bound_service_account_namespaces=...

# Login
vault write auth/my-k8s-cluster/login role=foo jwt=bar
```

In curl commands, that looks like:

```bash
curl -X POST -H "X-Vault-Request: true" -H "X-Vault-Token: $(vault print token)" -d '{"type":"kubernetes"}' $VAULT_ADDR/v1/sys/auth/my-k8s-cluster
curl -X PUT -H "X-Vault-Request: true" -H "X-Vault-Token: $(vault print token)" -d '{"kubernetes_host":"..."}' $VAULT_ADDR/v1/auth/my-k8s-cluster/config
curl -X PUT -H "X-Vault-Request: true" -H "X-Vault-Token: $(vault print token)" -d '{"bound_service_account_names":"...","bound_service_account_namespaces":"..."}' $VAULT_ADDR/v1/auth/my-k8s-cluster/role/foo
curl -X PUT -H "X-Vault-Request: true" -H "X-Vault-Token: $(vault print token)" -d '{"jwt":"bar","role":"foo"}' $VAULT_ADDR/v1/auth/my-k8s-cluster/login
```
