### ISSUE TITLE
clarification of service account authorization

### ISSUE THREAD

**Issue by swtch1** [hashicorp/vault-plugin-auth-kubernetes#55]
I am trying to fully understand the scope of this plugin.  I see that I can obviously authenticate a Kubernetes service account with Vault, but does this extend to letting me populate Kubernetes secrets and/or volumes with secrets from Vault?  I would like to use Vault as the backend for my secrets in Kubernetes.  If not, are you guys aware of something that fulfills this role?  If not I intend to build it.

**Comment by catsby** [comment]
Hello - this plugin specifically handles authentication with Vault using Kubernetes, and essentially nothing else. 

For injecting secrets from Vault into your pods, I recommend looking into [consul-template](https://github.com/hashicorp/consul-template) (which works with Consul and Vault), and possibly integrate it into a sidecar container.
