### ISSUE TITLE
Configuration fails if Host ends with a slash

### ISSUE THREAD

**Issue by NeilSorensen** [hashicorp/vault-plugin-auth-kubernetes#59]
If you configure the kubernetes host with a trailing slash (e.g. https://kube.example.com/), all requests will fail with a cryptic error message (it gets a 404 from Kubernetes, which results in a 500 from Vault).

This is caused by https://github.com/hashicorp/vault-plugin-auth-kubernetes/blob/master/token_review.go#L76, which adds a slash before the start of the path, regardless of whether the host ends in a slash.

Expected behavior: The host configuration should work either with or without the trailing slash. Whether that happens when configuration is entered or in the token_review.go, I don't care, but I shouldn't have to read your source code because I entered a valid URL as the host.

**Comment by catsby** [comment]
Fixed in #69 - thank you for reporting this and thanks for your patience
