### ISSUE TITLE
Vault should use it's own service account when using the TokenReview API

### ISSUE THREAD

**Issue by kelseyhightower** [hashicorp/vault-plugin-auth-kubernetes#6]
Users should be able to create workload service accounts without granting any permissions. This auth backend should use it's own service account so we can properly audit things in Kubernetes.

**Comment by destijl** [comment]
I think the rationale was you could create a cluster binding to grant tokenreview to all service accounts. So you can use whichever JWT you're verifying to talk to the TokenReview API.

Security-wise I think it's preferable to give vault a service account with TokenReview as you suggest. It's more configuration work to get things set up but we keep least privilege.
