### ISSUE TITLE
Do not make ca cert or pem keys required

### ISSUE THREAD

**Issue by bks7** [hashicorp/vault-plugin-auth-kubernetes#62]
What is the reason for having [ca cert or pem keys required](https://github.com/hashicorp/vault-plugin-auth-kubernetes/blob/master/path_config.go#L92)? It doesn't make sense for me since the ca cert is being used only for [establishing a connection to a kubernetes api](https://github.com/hashicorp/vault-plugin-auth-kubernetes/blob/master/token_review.go#L52). So for example, if you have kubernetes api behind AWS load balancer with a certificate from AWS certificate manager then you have to set either `kubernetes_ca_cert` with [one of the AWS root CA's](https://www.amazontrust.com/repository/) or set `pem_keys`. Setting public root CA looks odd to me. Setting `pem_keys` not always possible as described in  https://github.com/hashicorp/vault-plugin-auth-kubernetes/issues/3 and changed in https://github.com/hashicorp/vault-plugin-auth-kubernetes/pull/4. Maybe we can get rid of such behavior?  I think it won't make any harm because even if the kubernetes api would be secured with a self-signed certificate and a user would forget to set `kubernetes_ca_cert` he would  see just an error like this `x509: certificate signed by unknown authority"`, what makes clear to user that he needs to set `kubernetes_ca_cert` with appropriate ca cert.

**Comment by aleliaert** [comment]
Could the plugin default to using CAs within the host trust store?  My organization has K8s behind AWS LBs as well, seems odd to have to provide a public trusted CA cert.

**Comment by LittleChimera** [comment]
Looks like it might be enough just to change this to `x509.SystemCertPool()`

https://github.com/hashicorp/vault-plugin-auth-kubernetes/blob/9b38be8f9574147ff397c0dc0233c425c64eb6f8/token_review.go#L54

[x509.SYstemCertPool()](https://golang.org/pkg/crypto/x509/#SystemCertPool)
