### ISSUE TITLE
Docs should call out using the backend gives it some control over the cluster

### ISSUE THREAD

**Issue by destijl** [hashicorp/vault-plugin-auth-kubernetes#8]
Handing over K8s service account tokens to third parties is not an authentication behavior we want to encourage in general. In Vault's case this is likely to be acceptable in many environments since Vault tends to be the root of trust and an attack on the system requires control of Vault.

The long term plan is for K8s to make it easier for integrators to deliver their own creds via a solution being designed by the Kubernetes Container Identity Working Group:
https://docs.google.com/document/d/1bCK-1_Zy2WfsrMBJkdaV72d2hidaxZBhS5YQHAgscPI/edit

In the meantime the docs for this auth backend should make it clear that enabling it gives the Vault installation you're talking to control over the cluster. It should only be used with Vault installations that you trust with powerful access to your cluster.

**Comment by jefferai** [comment]
Hi Greg,

As you noted, technically Vault can abuse credentials given to it to perform actions within Kubernetes. However, this is not something unique to the Kubernetes auth mechanism; for any given authentication mechanism in Vault, credentials given to Vault have the possibility of being abused. For instance, one of the most popular mechanisms used is LDAP, and of course the same holds true for that backend as well. We try to be careful about only storing any sensitive information when needed, and of course, all data stored by Vault is encrypted at rest, but this is essentially "par for the course" for an authentication mechanism using real credentials.

When there are better approaches within Kubernetes we plan on migrating to them. We are aware of drawbacks with the given approach, and look forward to enhancing the plugin as possible, but at the end of the day needed to build something based on what was currently available while ensuring that the approach left open avenues for future enhancement as Kubernetes itself gains new capabilities.

If you have specific language you want to suggest feel free to send a PR, but this feels like a well-understood mechanism for Vault administrators.
