### ISSUE TITLE
vault HTTP/1.x transport connection broken: malformed HTTP response

### ISSUE THREAD

**Issue by get2arun** [hashicorp/vault-plugin-auth-kubernetes#80]
Hi Team,

I have deployed a sample application to talk vault server but having issues related to token it seems.

Environment:
Running minishift locally in ubuntu desktop. 

In the myproject namespace, vault is running.
In the vault-demo namespace, running the sample application using the below deployment.yaml

Expecting the application to login to vault server and kubernetes path mentioned in the environmental variables. but it is showing the error. It seems, some tokens are secrets are missing. 
![image](https://user-images.githubusercontent.com/18241061/71214499-3c46d280-2294-11ea-83d4-37e1b9e9d839.png)

**Please suggest what configuration is missing like any secrets or mount paths missing in the deployment.yaml file.** 

Below is the configuration of deployment.yaml file.
hashitvault$ cat deployment.yaml 
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: basic-example
  namespace: vault-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: basic-example
    spec:
      serviceAccountName: app1
      containers:
        - name: app
          image: "172.30.1.1:5000/vault-demo/vault-example-init:0.0.7"
          imagePullPolicy: Always
          env:
            - name: VAULT_ADDR
              value: "172.30.238.95:8200"
            - name: VAULT_ROLE
              value: "app1-role"
            - name: SECRET_KEY
              value: "secret/app1"
            - name: VAULT_LOGIN_PATH
              value: "auth/ocp/login"

The below is the ClusterIP of the VAULT SERVER.
            - name: VAULT_ADDR
              value: "172.30.238.95:8200"

**Comment by ChanderG** [comment]
I faced a similar error with kubernetes and the cause was the lack of the "imagePullSecrets" section in the config.

**Comment by tomhjp** [comment]
Sorry for the long delay here, but that "Malformed HTTP response" error looks like you are talking HTTP to an HTTPS endpoint. I imagine the `kubernetes_host` parameter in the Kubernetes auth method's config needs to be set to https://192.168.42.186:8443 in that example
