### ISSUE TITLE
pods are not starting in custom namespace.

### ISSUE THREAD

**Issue by balavs2806** [hashicorp/vault-plugin-auth-kubernetes#81]
vault-reviewer service-account.yaml
<--------------
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-reviewer
  namespace: app
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: vault-reviewer
  namespace: app
-------------------->

vault write  auth/kubernetes/login role=demo jwt="@sa.token"
Key                                       Value
---                                       -----
token                                     --------------------------------
token_accessor                            ----------------------------
token_duration                            48h
token_renewable                           true
token_policies                            ["default" "test-policy"]
identity_policies                         []
policies                                  ["default" "test-policy"]
token_meta_service_account_secret_name    vault-reviewer-token-9sv66
token_meta_service_account_uid            d62de135-8335-4a58-b2c2-263c8a4ce847
token_meta_role                           demo
token_meta_service_account_name           vault-reviewer
token_meta_service_account_namespace      app

the same configuration works for default workspace. but when i migrate it to different namespace, pod is not initialising. Moreover it doesnot shows any logs

**Comment by nitin-wise** [comment]
can you check deployment events ?

**Comment by tomhjp** [comment]
Going to close this in the absence of any updates, as there's also not enough detail to diagnose. At the very least we'd need to know:

* The auth/kubernetes/config values
* The role config
* The error message

Feel free to update with more details of how to reproduce though, or open up a topic at our [discuss forum](https://discuss.hashicorp.com/c/vault/30).
