### ISSUE TITLE
is it required for the sa to have cluster role, I created an service account with role and rolebinding however when i try to run it it says namespace not authorized

### ISSUE THREAD

**Issue by syprasha1994** [hashicorp/vault-plugin-auth-kubernetes#89]

**Comment by tomhjp** [comment]
There are two separate namespace controls to consider:

When you create a role, you can ask Vault to restrict with namespaces it's allowed to authenticate service accounts from:

```bash
vault write auth/kubernetes/role/my-role \
    bound_service_account_names="*" \
    bound_service_account_namespaces="my-app-namespace"\
    policies="my-policy" ttl=1h
```

Regardless of the Kubernetes setup, if you provide a JWT for a service account from any namespace other than `my-app-namespace`, this role will give you an unauthorized error. I believe this is probably what you're running into, and it is based purely on Vault configuration, so doesn't depend on any Kubernetes roles or cluster roles.

The other type of namespace control is where Kubernetes determines permissions based on namespaces. The Kubernetes auth method currently only uses the TokenReview API, which is a cluster-scoped resource. That means the `token_reviewer_jwt` used by Vault does indeed need a `ClusterRoleBinding`, where the `ClusterRole` most commonly used is `system:auth-delegator`.
