### ISSUE TITLE
Use pod service account instead of provided JWT for authentication

### ISSUE THREAD

**Issue by omerlh** [hashicorp/vault-plugin-auth-kubernetes#95]
Right now the auth method relies on `token_reviewer_jwt` as a way to supply the JWT for authentication. This makes it a lot harder to config when running the config as code (e.g. using Terraform). Why not just used the service account used by the pod? This is also support token projection API, which renew the tokens. Maybe this can be another config option? I'll be happy to open a PR

**Comment by davidmontoyago** [comment]
Not having to pass a literal secret to `token_reviewer_jwt` would be very useful indeed. For my use case, I'd prefer to keep the vault server identity separate from the service account that needs the `system:auth-delegator` ClusterRole.

What about allowing `token_reviewer_jwt` to take an environment variable? in that way we could have the vault server pods mount the secret with a reviewer service account token, like this:

```
env:
- name: VAULT_KUBE_AUTH_TOKEN
  valueFrom:
    secretKeyRef:
      name: vault-auth
      key: token
```

Happy to help with this feature as well.

**Comment by tvoran** [comment]
I believe this was covered by #122; closing for now.
