### ISSUE TITLE
Update JWT parsing to use a well-maintained library

### ISSUE THREAD

**Issue by lbordowitz** [hashicorp/vault-plugin-auth-kubernetes#96]
It makes more sense to use coreos/go-oidc rather than briankassouf/jose. The coreos repo appears very well maintained, as of today the last commit was 11 days old vs 2 years old. It also appears to have a more healthy community backing.

**Comment by calvn** [comment]
We're currently working on this in https://github.com/hashicorp/vault-plugin-auth-kubernetes/pull/148.

**Comment by swenson** [comment]
We switched to `golang-jwt` for now. We may switch to the Square fork of `jose` along with our HashiCorp `cap` in the future (see #149), though the checks there are too strict for Kubernetes 1.20 for now.
